### ISSUE TITLE
Fix directory of default install from github

### ISSUE THREAD

**Issue by erial** [theinvisible/tindexmenu#1]
I installed by github download ~/master.  It installed to 'theinvisible-tindexmenu'.

I doesn't work that states. 

I found it and change directory's name to 'indexmenu'.

Please fix that directory's name.

**Comment by theinvisible** [comment]
Hello,

yeah, thats still a issue coz the script is static linked to need the "indexmenu" directory.

wernerflamme made some patches, i will merge them so the plugin directory must be named "tindexmenu"

Regards
