### ISSUE TITLE
use of deprecated function search_callback in syntax/indexmenu.php

### ISSUE THREAD

**Issue by fa-ribeiro** [theinvisible/tindexmenu#10]
There is a bunch of calls to deprecated function search_callback in indexmenu.php.
This function was removed from dokuwiki trunk, so it crashes the site.
I made a workarround by copy/paste the function into the action.php file.

/**
- Wrapper around deprecated search_callback.
  *
- @deprecated
  */

function search_callback($func,&$data,$base,$file,$type,$lvl,$opts){
    return call_user_func_array($func, array(&$data,$base,$file,$type,$lvl,$opts));
}

**Comment by theinvisible** [comment]
Hi,

thanks for the information, it will be included in the next commit.
